[build]
  command = "npm run netlify-build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  PRISMA_GENERATE_SKIP_AUTOINSTALL = "true"
  # Use pooled connection string for Prisma in serverless
  # DATABASE_URL and DIRECT_URL must be set in Netlify UI

# Use Netlify's Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle static assets with proper caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle font files
[[headers]]
  for = "/_next/static/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
