[build]
  command = "npm run netlify-build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  # Prevent dependency lifecycle scripts (e.g. prepare/postinstall) from running during install.
  # Some packages try to run `rollup -c` in prepare, which fails on Netlify.
  # We generate Prisma client explicitly in the build command, so this is safe.
  NPM_FLAGS = "--ignore-scripts --no-audit --no-fund"
  PRISMA_GENERATE_SKIP_AUTOINSTALL = "true"
  # Use pooled connection string for Prisma in serverless
  # DATABASE_URL and DIRECT_URL must be set in Netlify UI

# Use Netlify's Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle static assets with proper caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle font files
[[headers]]
  for = "/_next/static/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
